version = 0.1
[default.deploy.parameters]
stack_name = "webpage-analyzer"
resolve_s3 = true
s3_prefix = "webpage-analyzer"
region = "eu-west-3"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
